version: "3.7"

services:
  # api service
  s_cool_api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: 
      - .env
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    networks:
      - cool_api_network

# shared network
networks:
  cool_api_network:
    driver: bridge

